from constants.expressions import EXPR_TIME_SERVICE_FILEBACKUP
from constants.secrets import SEC_SYSTEM_FILES

DEFAULT_NOTIFICATION_TARGET = "home"

# Log

CFG_LOG_FILE = "home-assistant.log"
CFG_LOG_SIZE = 24
CFG_LOG_TAIL = 8

CFG_LOG_ARCHIV_SIZE = 32768
CFG_LOG_ARCHIV_SUFFIX = "2"
CFG_LOG_HISTORY_SIZE = 128
CFG_LOG_HISTORY_SUFFIX = "1"

CFG_LOG_LOGGER = "py"
CFG_LOG_LEVEL = "info"

CFG_LOG_SETTINGS_IO_RETRY = 3
CFG_LOG_SETTINGS_DELAY_BLOCK = 5

CFG_LOGFILE_FORMAT = "%(asctime)s: %(message)s"
CFG_LOGFILE_LOG_SIZE = 256
CFG_LOGFILE_DEBUG_FILE = "messages"

CFG_LOGFILE_DEBUG_FUNCTION_STARTED = False

# Events

CFG_EVENT_STARTED_DELAY = 3

# Paths

CFG_PATH_DIR_CONFIG = "/config"
CFG_PATH_DIR_LOG = f"{CFG_PATH_DIR_CONFIG}/logs"
CFG_PATH_DIR_FILES = f"{CFG_PATH_DIR_CONFIG}/files"
CFG_PATH_DIR_STORAGE = f"{CFG_PATH_DIR_CONFIG}/.storage"

CFG_PATH_DIR_PY = f"{CFG_PATH_DIR_CONFIG}/pyscript"
CFG_PATH_DIR_PY_LOGS = f"{CFG_PATH_DIR_PY}/logs"
CFG_PATH_DIR_PY_NATIVE = f"{CFG_PATH_DIR_CONFIG}/pyscript/python"

CFG_PATH_LOG = f"{CFG_PATH_DIR_CONFIG}/{CFG_LOG_FILE}"

CFG_PATH_DIR_PY_SUPERVISOR = "/homeassistant"
CFG_PATH_DIR_PY_SUPERVISOR_LOGS = f"{CFG_PATH_DIR_PY_SUPERVISOR}/logs"
CFG_PATH_DIR_PY_SUPERVISOR_LOG = f"{CFG_PATH_DIR_PY_SUPERVISOR}/{CFG_LOG_FILE}"

# Services

CFG_SERVICE_ENABLED_AIR_CONTROL = False
CFG_SERVICE_ENABLED_SYNC_GIT = False
CFG_SERVICE_ENABLED_SCRAPE_HOUSING = True

CFG_SERVICES_INIT = {'shell_command.filebackup': EXPR_TIME_SERVICE_FILEBACKUP}

# System

CFG_SYSTEM_ENVIRONMENT = {
  "PYTHONDONTWRITEBYTECODE": "1",
  "ZDOTDIR": f"{CFG_PATH_DIR_STORAGE}/zsh"
}

CFG_SYSTEM_FILES = {**SEC_SYSTEM_FILES, f"{CFG_PATH_DIR_FILES}/.zshrc": f"{CFG_SYSTEM_ENVIRONMENT['ZDOTDIR']}/.zshrc"}

CFG_SYSTEM_LINKS = {
  CFG_PATH_DIR_PY_SUPERVISOR_LOGS: CFG_PATH_DIR_PY_LOGS,
  CFG_PATH_DIR_PY_SUPERVISOR_LOG: f"{CFG_PATH_DIR_LOG}/{CFG_LOG_FILE}",
  f"{CFG_PATH_DIR_PY_SUPERVISOR_LOG}.{CFG_LOG_HISTORY_SUFFIX}": f"{CFG_PATH_DIR_LOG}/{CFG_LOG_FILE}.{CFG_LOG_HISTORY_SUFFIX}",
  f"{CFG_PATH_DIR_PY_SUPERVISOR_LOG}.{CFG_LOG_ARCHIV_SUFFIX}": f"{CFG_PATH_DIR_LOG}/{CFG_LOG_FILE}.{CFG_LOG_ARCHIV_SUFFIX}"
}