from homeassistant.const import STATE_ON, STATE_OFF, STATE_UNAVAILABLE, STATE_UNKNOWN

MAP_STATE_HA_TIMER_IDLE = "idle"
MAP_STATE_HA_UNDEFINED = [STATE_UNAVAILABLE, STATE_UNKNOWN]
MAP_STATE_UNDEFINED = [MAP_STATE_HA_UNDEFINED, "", None, "None", type(None), "NoneType"]

MAP_SERVICE_HA_TURNOFF = "homeassistant.turn_off"

MAP_EVENT_FOLDER_WATCHER = "MAP_EVENT_FOLDER_WATCHER"
MAP_EVENT_HOUSING_INITIALIZED = "MAP_EVENT_HOUSING_INITIALIZED"
MAP_EVENT_NEVER = "MAP_EVENT_NEVER"
MAP_EVENT_SYSTEM_STARTED = "MAP_EVENT_SYSTEM_STARTED"

PERSISTENCE_ENTITY_AUTO_PRESENCE = "pyscript.auto_presence"
PERSISTENCE_PREFIX_PREFIX = "timer"
PERSISTENCE_PREFIX_SENSOR_SCRAPE_HOUSING = "v_scrape"

MAP_SERVICE_ID_NOTIFICATION_CHANGEDETECTION = "changedetection"
MAP_SERVICE_AIR_CONTROL_MODE_SLEEP = "sleep"
MAP_SERVICE_SCRAPE_HOUSING_SHORTCUT_NAME = "SC-HA-Notify-Housing"