from homeassistant.const import STATE_ON, STATE_OFF, STATE_UNAVAILABLE, STATE_UNKNOWN

MAP_STATE_HA_TIMER_ACTIVE = "active"
MAP_STATE_HA_TIMER_IDLE = "idle"
MAP_STATE_HA_UNDEFINED = [STATE_UNAVAILABLE, STATE_UNKNOWN]

MAP_STATE_UNDEFINED = [STATE_UNAVAILABLE, STATE_UNKNOWN, "unknown", "", None, "None", type(None), "NoneType"]

MAP_EVENT_FOLDER_WATCHER = "FOLDER_WATCHER"
MAP_EVENT_HOUSING_INITIALIZED = "MAP_EVENT_HOUSING_INITIALIZED"

MAP_EVENT_NEVER = "MAP_EVENT_NEVER"

MAP_EVENT_SETUP_STARTED = "MAP_EVENT_SETUP_STARTED"
MAP_EVENT_SYSTEM_STARTED = "MAP_EVENT_SYSTEM_STARTED"

MAP_PERSISTENCE_ENTITY_PRESENCE = "pyscript.presence"
MAP_PERSISTENCE_PREFIX_TIMER = "timer"
MAP_PERSISTENCE_PREFIX_SCRAPE_HOUSING = "scrape"

MAP_RESULT_STATUS = ["STARTED", "STOPPED", "CANCELED"]

MAP_SERVICE_HA_TURNOFF = "homeassistant.turn_off"

MAP_SERVICE_ID_NOTIFICATION_CHANGEDETECTION = "changedetection"
MAP_SERVICE_AIR_CONTROL_MODE_SLEEP = "sleep"
MAP_SERVICE_SCRAPE_HOUSING_SHORTCUT_NAME = "SC-HA-Notify-Housing"
