# Paths

SET_SUBPROCESS_COMPILE_PATH="/share/extern/Sicherungen/Pi/compile"
SET_SUBPROCESS_FILEBACKUP_FOLDER = "/share/extern/Sicherungen/Pi"

# Automation

SET_CONTROL_ON_LONG_DURATION = 60
SET_CONTROL_ON_LONG_HOLD = 2
SET_MOTION_TIMEOUT = 70

SET_OFF_AWAY_TRANSITION = 20

SET_ENTITIES_GLOBAL_VOLUME_MAX =20

# Services

SET_AIR_CONTROL_CLEAN_MODE_PERCENTAGE = 50
SET_AIR_CONTROL_SLEEP_MODE_PERCENTAGE = 15
SET_AIR_CONTROL_HELPER_PM_MINIMUM = 8
SET_AIR_CONTROL_SPEED_THRESHOLD = 30
SET_AIR_CONTROL_THRESHOLD_RETRIGGER_DELAY = 900
SET_AIR_CONTROL_THRESHOLD_START = 8
SET_AIR_CONTROL_THRESHOLD_STOP = 2
SET_AIR_CONTROL_TIMEOUT_CLEAN = 480
SET_AIR_CONTROL_TIMEOUT_HELPER = 240
SET_AIR_CONTROL_WAIT_ACTIVE_DELAY = 1
SET_AIR_CONTROL_WAIT_ACTIVE_RETRIES = 3


SET_SCRAPE_HOUSING_BLACKLIST = [
  "WBS erforderlich", "mit WBS", "WBS 160", "Wohnberechtigungsschein erforderlich", "Seniorenwohnung",
  "nur mit WBS", "nur WBS", "nur mit Wohnberechtigungsschein", "mit Wohnberechtigungsschein", 
  "WBS 140", "WBS Pflicht", "WBS benötigt", "nur für WBS Inhaber", "wbs pflichtig", "wbs-pflichtig"
]
SET_SCRAPE_HOUSING_DELAY_RANDOM_MIN = 1
SET_SCRAPE_HOUSING_DELAY_RANDOM_MAX = 301
SET_SCRAPE_HOUSING_FILTER_AREA = 50
SET_SCRAPE_HOUSING_FILTER_PLZ = ['12043', '12045', '12047', '12049', '12051', '12053', '13573', '12089']
SET_SCRAPE_HOUSING_FILTER_RENT = 680
SET_SCRAPE_HOUSING_FILTER_ROOMS = 2
SET_SCRAPE_HOUSING_SENSOR_LENGTH = 254

SET_SUBPROCESS_FILEBACKUP_RETENTION = 7