AUTO_CONFIG_MOTION_SUNSET_DIFF = 30
AUTO_CONFIG_MOTION_TRANSITION = 20
AUTO_CONFIG_MOTION_TIMEOUT = 60

EVENT_FOLDER_WATCHER = "folder_watcher"

HA_PATH_LOG = "/config/home-assistant.log"
HA_PATH_LOG_ARCHIVE = "/config/home-assistant.archive.log"

HA_STATE_NONE = "None"
HA_STATE_UNAVAILABLE = "unavailable"
HA_STATE_UNKNOWN = "unknown"

HA_STATES_UNDEFINED = [HA_STATE_NONE, HA_STATE_UNAVAILABLE, HA_STATE_UNKNOWN]

SIZE_LOG_ENTRIES = 10
SIZE_LOG_ARCHIVE_ENTRIES = 10