EXPR_STATE_SEASON_POLLEN = "sensor.season in ['spring', 'summer']"
EXPR_STATE_OPEN_WINDOW = "sensor.open_window == 'true'"
EXPR_TIME_ACTIVE =  "cron(* 9-19 * * 1-6)"
EXPR_TIME_RANGE_DAY = "range(00:00, 24:00)"
EXPR_TIME_UPDATE_SENSORS = "cron(30 16 * * 1-7)"
EXPR_TIME_ACTIVE_RANGE_EVENING = "range(19:00, 24:00)"
EXPR_TIME_ACTIVE_RANGE_NIGHT = "range(24:00, 6:00)"