STATE_ON = "on"

# script_air_cleaner

SCRIPT_AIR_CLEANER_ENTITY = "fan.luftreiniger"
SCRIPT_AIR_CLEANER_ENTITY_ATTRIBUTE = "percentage"
SCRIPT_AIR_CLEANER_ENTITY_MODE = "mode"
SCRIPT_AIR_CLEANER_HELPER = "switch.sz_luftung"
SCRIPT_AIR_CLEANER_SENSOR = "sensor.luftreiniger"

SCRIPT_AIR_CLEANER_PRESET_MODE_MANUAL = "manual"
SCRIPT_AIR_CLEANER_PRESET_MODE_SLEEP = "sleep"